### ISSUE TITLE
Find literature

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/SE17_TeamH_Ideas#1]
Find literature on all the ideas, and narrow the ideas to at most 5.

**Comment by DevArenaCN** [comment]
I've tried my best to find several literature on those topics assigned to me, so far I think mine is done. Let me know where I can contribute some input on yours.

**Comment by thegreyd** [comment]
Yes. So I've narrowed down a little - dropped health management, price aggregation. Do i open issues for ideas i think are worthy or we first discuss the final 5-6, and then open for each of them?

**Comment by DevArenaCN** [comment]
Let's hold off creating each topic as issues until we narrow them down first.

**Comment by thegreyd** [comment]
Sure. Do we continue discussing them here or a new issue, for the final topic list?

**Comment by DevArenaCN** [comment]
Let's continue discuss them here, and once we narrow them down, we can make separate ones and discuss each of those under those separated issues.

**Comment by thegreyd** [comment]
Password management is a strong candidate. Has literature, many ways; user reviews will be possible.

(Thumb up for approval, thumb down if not too exciting.)

**Comment by DevArenaCN** [comment]
👍. Is there anything we can use for this? APIs or open source projects available?

**Comment by thegreyd** [comment]
Some open source projects I know personally of:
- [KeepassX](https://github.com/keepassx/keepassx) : cross platform Desktop client, for password management, has features for random password generation.
- [KeeWeb](https://github.com/keeweb/keeweb) : Implemented with web technologies, has similar features
- [Diceware](https://github.com/ulif/diceware/) : For passphrase generation.

**Comment by DevArenaCN** [comment]
Update some papers on the issue in the Papers folder. Pull request #10
