### ISSUE TITLE
adding literature abstracts to README under /papers

### ISSUE THREAD

**Issue by KaustubhG** [SE17GroupH/SE17_TeamH_Ideas#11]
Hey guys,
Could you add the abstracts and links of the literature found in the README under **/papers**. It will provide a better overview of the literature we have found.

**Comment by DevArenaCN** [comment]
I've updated abstract for those pdf files in Papers folder. For those papers in the README file, could you guys download or save those papers to PDF then commit those files onto Papers folder? It'll be easier for others to read. Thanks!

**Comment by KaustubhG** [comment]
done! :)
