### ISSUE TITLE
Upload research papers onto github under Papers folder

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/SE17_TeamH_Ideas#12]
Upload those papers onto GitHub so that it's easier for others to read. 

HOW TO DO:
First clone this GitHub repo to your local machine using command `git clone https://github.com/SE17GroupH/SE17_TeamH_Ideas.git`

Then you could create your own branch to do it, or you can just do it on the master branch in this case since we're just making a file repo on GitHub. After putting all the pdf files you want to upload to your local storage in the Papers folder, you can just use the command `git commit -a -m "commit message"` to commit those files.

The last step is using `git push` to upload those files onto the current repo.

**Comment by KaustubhG** [comment]
done! :)

**Comment by DevArenaCN** [comment]
Thanks!
