### ISSUE TITLE
this is a GREAT list

### ISSUE THREAD

**Issue by timm** [SE17GroupH/SE17_TeamH_Ideas#13]
truly impressive

https://github.com/SE17GroupH/SE17_TeamH_Ideas/blob/master/ideasDoc.md

i take it you are assessing each idea via

- how much lit you can find on each?
- whether or not you can find a clear eval criteria?
- whether or not you can code your ideas in an early-march timeframe?

**Comment by thegreyd** [comment]
Yes that's what we had in mind.

**Comment by thegreyd** [comment]
And we wanted your feedback on some of these. Hopefully we can meet during tomorrow's office hours before class?

**Comment by thegreyd** [comment]
Resolved
