### ISSUE TITLE
Prepare Questionnaire for user-feedback

### ISSUE THREAD

**Issue by KaustubhG** [SE17GroupH/SE17_TeamH_Ideas#19]

**Comment by KaustubhG** [comment]
Questions:
How often do you forget your password ?
How many passwords/accounts do you have on average?
Would you like an authentication system, that does away with remembering passwords?
How do you feel about fingerprints as a biometric?
How do you feel about voice used as a biometric for authentication?

**Comment by KaustubhG** [comment]
@thegreyd  @DevArenaCN  prepared a questionnaire and added you guys as collaborators. Have a look at it :)

**Comment by DevArenaCN** [comment]
The site is online at [here](http://tiny.cc/loginExp), we could add this into the survey.

**Comment by DevArenaCN** [comment]
- How many tries did it take for you to log in a system?

- How often do you change your password?

- Have you ever used any biometric ways such as fingerprints or face recognition as a password?

- How do you like those biometric authentication methods?

- Do you feel safe when entering your password online?

- Do you have a mobile device that has a biometric sensor (e.g. TouchID, fingerprint scanner)

- How many passwords do you have? (we don't need to ask THEM about the average, that's something for us to do)

- How do you input your password? (A, input everytime using keyboard/touchscreen   B, remember password in web browsers(e.g. Chrome)    C, Password management software autofill(e.g. 1Password)  D, Others)

**Comment by DevArenaCN** [comment]
@thegreyd Any input you wanna add to the questionnaire?

**Comment by thegreyd** [comment]
Yes I am reviewing them. Are you creating a form? I'll confirm soon.

**Comment by thegreyd** [comment]
I think the theme of questionnaire would be to know 
- how users feel about existing authentication methods
    - problems
    - usage
- how users feel about alternate authentication methods

I'm also referring to these surveys:
- https://www.roboform.com/blog/password-security-survey-results
- https://www.surveymonkey.com/r/password-survey
- https://www.symantec.com/connect/blogs/password-survey-results

**Comment by thegreyd** [comment]
- You would you describe your computer usage as 
	- home
	- office
	- technical
- Do you use 
	- password manager
	- browser to store your passwords
	- save them in document/note
	- memory
	- physically note them
- How many passwords do you have
- How many passwords/passphrases/pin do you remember at any one time
- How many different passwords do you use?
- How do you choose passwords for these websites
	- They are all the same (with maybe few modifications)
	- i have a few passwords and I alternate between them
	- a few duplicate but mostly unique
	- unique passwords for each account
- how often do you change your passwords?
	- very rarely
	- Once in a year
	- half-yearly
	- quarterly or more often
- Most important factor in authentication
	- secure
	- easy/convenient

**Comment by DevArenaCN** [comment]
@thegreyd this is a great list. I think we can use this one, but I want to add some questions regarding biometric sensors into the survey since we're trying to use them, and we would like to know if most people have them on their mobile device right now.

**Comment by thegreyd** [comment]
Thanks Harold :) Yes we need to add more questions regarding mobile, and alternate authentication methods. I am writing them now, will share soon. Do suggest yours as well

**Comment by thegreyd** [comment]
- Do you think text based authentication is not secure?
	- Yes
	- No

- Do you think text based authentication is not easy to use?
	- Yes
	- No

- Do you think text based authentication should be replaced with something else?
	- Yes
	- No


- Which of these have you used for authentication?
	- fingerprint/biometrics
	- facial recognition
	- voice recognition
	- device based (usb/smartphone/smartcard)
	- audio-visual based passphrase/password

- Which of these would you prefer instead of text based username/password?
	- fingerprint/biometrics
	- facial recognition
	- voice recognition
	- device based (usb/smartphone/smartcard)
	- audio-visual based passphrase/password

- Do you own a device with a biometric/fingerprint sensor?
	- yes
	- no

**Comment by KaustubhG** [comment]
@DevArenaCN @thegreyd  I had created you guys as collaborators to the questionnaire I created earlier.
Here is the link: https://docs.google.com/a/ncsu.edu/forms/d/1PTz_F8vUXttOh2PGY9BLE2mtogEKse_l02lt2nqxnQ8/edit?usp=sharing

Add your questions/modifications to it.

**Comment by DevArenaCN** [comment]
I've add a section for the user login experiment site.

**Comment by DevArenaCN** [comment]
Need to make changes to the questionnaire. From slack message by the professor:

> Please ensure your surveys, interviews etc include a chit number (@efarhan sent those out over the weekend). otherwise, folks wont be able to “spend” their eval credits
>  also,
> 0) the survey at https://goo.gl/SNFv3n needs to satisfy our 3 rights. e.g. a question “do you wish to NOT fill out this survey”. and my name is XYZ and I am administrating this survey and I commit to you the following policies (then you include text about right to privacy and right to be forgotten)
> 1) when folks get survey responses, they need to collect the chits and pass along (with their deliverables) the chits they collected from their subjects.
> 2) and everyone else’s collection instruments need the same as (0

I can do it after work, but if you guys have the time and wanna do it early let me know.

**Comment by DevArenaCN** [comment]
I've updated the survey, I'm going to make some changes to the user login experiment site with some instructions on the homepage. Feel free to edit the survey. I think I made all the changes I wanted on it.

**Comment by DevArenaCN** [comment]
I've updated the experiment site with instructions on the homepage, and a link with tutorials.

**Comment by DevArenaCN** [comment]
We got 50 responses from the survey so far, and I'm seeing 18 entries for the dummy site.

**Comment by DevArenaCN** [comment]
78 responses. Great work guys. I'm closing this issue.
