### ISSUE TITLE
Prepare specifics to be discussed during user-interviews

### ISSUE THREAD

**Issue by KaustubhG** [SE17GroupH/SE17_TeamH_Ideas#20]

**Comment by KaustubhG** [comment]
Interviewing users:

1. Ask them to log-in into the test login system.
2. Ask them to log-in into a bunch of legit accounts (facebook, gmail, etc.)
3. Discuss about text-based passwords.
4. Discuss about biometrics being used as auth methods.

**Comment by DevArenaCN** [comment]
Done with this issue. Closing it now.
