### ISSUE TITLE
Pre User-feedback Meeting notes

### ISSUE THREAD

**Issue by KaustubhG** [SE17GroupH/SE17_TeamH_Ideas#22]
Questionnaire
-Google forms
-Look at past questionnaires
-Post sign-up sheets on slack

Interviews
-things to note down
-dummy login system ?
-book rooms
-cookies
-measuring login time

**Comment by DevArenaCN** [comment]
Regarding cookies for today, cooked a batch last night, not even near as good as I hoped, so we might need to get some from the cafeteria.

**Comment by KaustubhG** [comment]
Sure

**Comment by DevArenaCN** [comment]
Done with user meeting.Closing this issue
