### ISSUE TITLE
Prepare schedule to conduct user meetings

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/SE17_TeamH_Ideas#23]
Hey guys,
Please comment on, the time you are free this week - each day and time of the day. 2 of us can conduct one session of survey if all 3 are not free.

**Comment by DevArenaCN** [comment]
I'm free all day Tuesday, Thursday before 4:30 PM, and Friday all day.

**Comment by KaustubhG** [comment]
Mon-Wed : All day except 3:15-4:30PM
Tue-Thurs: 9:00-11:30 AM
Friday: All day

**Comment by thegreyd** [comment]
Mon-Tue-Thurs : 11:00-4:00pm
Wed : 11:00-4:00 pm and 6:00-9:00 pm
Friday - all day

**Comment by thegreyd** [comment]
I'll try and get a common schedule prepared

**Comment by thegreyd** [comment]
Mon - 11-3 : siddharth and kaustubh
Tue - 11-3 : Harold, sid and kaustubh - we can split or something - can take in more people than monday if we all are present.
Wed - 11-3 : Sid and Kaustubh

I was thinking let's just plan and put up sheet for these initial 3 days. We can adjust accordingly based on them, and put up a new sign up sheet

**Comment by thegreyd** [comment]
The signup sheet is here, please take a look : https://goo.gl/5AUhos

**Comment by thegreyd** [comment]
Is the schedule okay? We can go ahead and book rooms accordingly

**Comment by thegreyd** [comment]
I'm putting up the sign up sheet on slack group. Interviews starting from tomorrow in hunt library room 3314 (booked it).

**Comment by DevArenaCN** [comment]
Cool. Great work guys. I'm gonna ask some of my friends to participant as well, probably won't using the signup sheet for it though

**Comment by KaustubhG** [comment]
Jan 24 Tuesday: Room 3313 booked: 12:30 PM - 4:30 PM
Jan 25 Wednesday: Room 2323 booked: 10:30 AM - 2:30 PM

**Comment by DevArenaCN** [comment]
How's yesterday's user meeting goes? Any issue we need to worry about for today's user meeting?

**Comment by DevArenaCN** [comment]
Done with this issue. Closing it now.
