### ISSUE TITLE
Trying to get a workable user reg/login system by Sunday

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/SE17_TeamH_Ideas#24]
Working on a user register/log in system for experiment. Not sure if I can get this done but I'll try my best.

**Comment by DevArenaCN** [comment]
I created a new repo for it. Link is [here](https://github.com/SE17GroupH/userLoginExperiment). I'm using Ruby on Rails for this cause I think it'll be easier for me to do. Feel free to check it out and make changes to it, as long as you guys created a new branch. Please let me know before hand so that I can create my own branch

**Comment by DevArenaCN** [comment]
Have a working version that can record how long it took the user to successfully log in, can't think of a way to log one scenario, which is if the user failed to log in once, or even more than one time, but successfully logged in in the end, it can only record that only one try that let the user successfully logged in. Don't know if we should resolve it or not, I'm trying another approach tomorrow. Latest code is in [here](https://github.com/SE17GroupH/SE17_TeamH_Ideas/tree/master/userLoginExp) and  [here](https://github.com/SE17GroupH/SE17_TeamH_Ideas)

**Comment by KaustubhG** [comment]
@DevArenaCN  This is awesome!! 😄  👍

**Comment by DevArenaCN** [comment]
Site is up and running at [here](http://tiny.cc/loginExp)
