### ISSUE TITLE
Creating latex file for final report

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/SE17_TeamH_Ideas#30]
We need to have a latex file for our January report. Does anyone have a sharelatex account that can add collaborators?

**Comment by DevArenaCN** [comment]
Latex file is created via ShareLatex [here](https://www.sharelatex.com/project/588b6d896e5de4073270d58b)

**Comment by thegreyd** [comment]
Can you add me Harold. My mail id is: sid dot sharma0 at gmail.com

**Comment by DevArenaCN** [comment]
@thegreyd done

**Comment by DevArenaCN** [comment]
I have added sections and subsections in the latex file, add more however you guys see fit. Let me know if you guys are having issue accessing or editing the latex file via sharelatex.

**Comment by KaustubhG** [comment]
created a rough draft of abstract and intro. Will work on the literature review tonight

**Comment by DevArenaCN** [comment]
Updated the literature review and user survey part in sharelatex. Could any of you gather some information, papers on fingerprint authentication and voice authentication and write some review in the literature review section? 

Also, I'm thinking creating a tradeoff table for the conclusion section, which we will show the tradeoffs between traditional text-based password, fingerprints, voice, and the email-based one. I'm thinking we can compare the easy-to-use, need remembering, offline ability, security, accuracy, let me know what you guys think or what we can add to the tradeoff table. Thanks!

**Comment by DevArenaCN** [comment]
Added conclusion and new content to data analysis section. Please edit those as you see fit!

**Comment by thegreyd** [comment]
Yes I'll edit and add content to those sections soon. Thanks @DevArenaCN !

**Comment by KaustubhG** [comment]
yeah, me too

**Comment by thegreyd** [comment]
Closing this. We can continue talking at #5
