### ISSUE TITLE
Gather documents for January report

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/SE17_TeamH_Ideas#31]
We need a place to note everything that we could use in this report, so I open up this issue.

- For papers, note down which paragraph or which line you would like to add into the report.

- For user meeting, survey notes, put it in the Google doc file [here](https://docs.google.com/document/d/1DDpc6n4fV3IhqgETgoCY_edMnC3erDfRm0szOl5aFpQ/edit)

- For graphs, tables, please note which paper they're from and which graph, or comment with a link to the graphs/table.

**Comment by KaustubhG** [comment]
Paper:

Abstract - kg
Intro - kg
Literature Review - kg, harold, siddharth
Survey (User Study)
Conclusion

**Comment by KaustubhG** [comment]
I can do the abstract and the intro
We all can chip in for the lit. review.

**Comment by DevArenaCN** [comment]
[refer link](https://www.sharelatex.com?r=51e41f09&rm=d&rs=b)

**Comment by thegreyd** [comment]
Yes I'll enter the details of interviews in google doc. However I can't see the survey results.

**Comment by DevArenaCN** [comment]
@thegreyd Let me know which gmail account you need the access, I'll try to add you into it

**Comment by DevArenaCN** [comment]
Done with document gathering. Closing this issue
