### ISSUE TITLE
Find a cool project name

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/SE17_TeamH_Ideas#33]
Let's note down our ideas of cool project names and select the most agreeable one. It can be our heading to our paper and presentation. 

Will close this issue tomorrow.

**Comment by thegreyd** [comment]
- Forgot Password? : Exploring alternate ways of Authentication
The rationale behind this one: It's very recognizable, because every website has, everyone has pressed that button sometime. Plus it shows the weakness in text passwords, which we are trying to solve.

**Comment by thegreyd** [comment]
- "I'm sorry Dave, I'm afraid I can't do that"
A famous movie quote and [scene from 2001:Space Odyssey](https://www.youtube.com/watch?v=ARJ8cAGm6JE), about a computer AI refusing to allow a human to enter inside a space ship. That's our metaphor for a system not letting user in, when the user is real but he is not able to prove it.

**Comment by thegreyd** [comment]
- The Oracle
Oracle is someone who delivers prophecies of God. Don't know how that relates, but sounds cool.

**Comment by thegreyd** [comment]
- The weakest link
It references the idea that in a security system, the weakest link in most scenarios is the user. While strong passwords are cryptographically secure, users repeat their passwords, use short length passwords or very common phrases; use downright idiotic ones like "12345". We are potentially changing that, by making security accessible.

**Comment by timm** [comment]
The Flash
History of the World parts 1,2,3
A Theory of Everything
Give me all your money, now.
We are the champions... of the world

**Comment by thegreyd** [comment]
Thanks professor those are helpful. Another one from me:
- HaveIbeenPwned?
Inspired by the [very useful website haveibeenpwned](https://haveibeenpwned.com/) which checks if your account information has been compromised, in data hacks over the years.

**Comment by KaustubhG** [comment]
Here is one from me:
I am not a robot: Exploring authentication systems easier for the USer.

Inspired by: Making us remember so many different passwords with so many policies is like assuming we are robots. We need to make authentication easier for 'US' (i.e the user)

The title is thought from the check box you need to click to verify that you are a human being!

**Comment by KaustubhG** [comment]
Sign me in already! : Replacing the barbaric and cumbersome text-based passwords.

Inspired by: Signing in into some website takes way too long and remembering weird and long passwords seems barbaric in the age of biometric scanners and other cool technologies!

**Comment by timm** [comment]
Already In
Inned (logged in)
Greased (can move faster)
Zap! (zap, you are in)

**Comment by KaustubhG** [comment]
I like the zap one :)

**Comment by thegreyd** [comment]
Wow a flood of good ideas :D

**Comment by thegreyd** [comment]
Let's select the top 3 and then we can vote?

**Comment by thegreyd** [comment]
Or let's go with Zap! if we all agree

**Comment by DevArenaCN** [comment]
I'm cool with Zap!

**Comment by thegreyd** [comment]
Finalizing Zap! as the project name. Thanks for the feedback everyone!
