### ISSUE TITLE
Create presentation and prepare lightning talk

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/SE17_TeamH_Ideas#34]

**Comment by thegreyd** [comment]
Some xkcd comics for presentation : https://xkcd.com/538/, https://xkcd.com/565/

**Comment by DevArenaCN** [comment]
Slide can be found [here](https://docs.google.com/presentation/d/1DXsgowAAuM34EEAHN0AY8hpeM97dWQZB16-gelvl6ow/edit#slide=id.gd251bb473_0_681)

**Comment by DevArenaCN** [comment]
Done with the lightning talk preparation. Talk script is in the note on Google Slide. Let me know what you guys think. Thanks!

**Comment by thegreyd** [comment]
here's my feedback. The color combination and layout is great! But since every slide will be up for 20 seconds, slides with only one word would need some modification.

**Comment by thegreyd** [comment]
Maybe we can add exxamples of existing implementation like graphical password, and face recognition in Windows 10, use of magic links in medium, fingerprint in ios

**Comment by DevArenaCN** [comment]
@thegreyd Fair point, but my consideration is that only key talk points would be on the slide, since we want people's attention on the speaker, not the slide itself. For the examples, yes I will put that in tonight.

**Comment by KaustubhG** [comment]
Great presentation!
Here is my feedback:
The organization is great and supported with data where required :-)

I feel we should support the Why part with some literature too.
Maybe we could add some literature and/or some comic which says something on the lines of 
'text-based passwords are really annoying/tedious/difficult to manage... etc.

Also the color scheme changes to a black background for some slides. That feels a bit abrupt.

**Comment by KaustubhG** [comment]
Here are some pointers:
https://www.smashingmagazine.com/2016/06/the-current-state-of-authentication-we-have-a-password-problem/

**Comment by DevArenaCN** [comment]
Alrighty. I'll make some changes

**Comment by DevArenaCN** [comment]
@thegreyd I kinda misunderstood your first statement. I'll make some changes

**Comment by DevArenaCN** [comment]
I've added some content from the papers we used into the slide, as for the single word, I'll make some test runs to see if I can get at least 15 seconds into it, if not, I'm gonna get rid of those single word slides. As for the black ground, that's what comes with the template, I'm not in favor of changing it, the reason for that is those 4 slides are on a different track with what I'm presenting next, I can change it if you guys feel more comfortable using the same background color. @thegreyd  for the existing examples, could you go into more detail? Such as do I need to create a new segment for it? Or just simply add it to the How section?
