### ISSUE TITLE
Magic link resources

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/SE17_TeamH_Ideas#35]

**Comment by thegreyd** [comment]
- https://github.com/aaugustin/django-sesame
- https://github.com/auth0/lock-passwordless

**Comment by DevArenaCN** [comment]
[Auth0 with Android](https://auth0.com/docs/libraries/lock-android/passwordless-magic-link)

**Comment by DevArenaCN** [comment]
Move it to another repo. Close this one.
