### ISSUE TITLE
Prepare report for Project Phase 1

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/SE17_TeamH_Ideas#5]
Use the documentation from the literature on Google scholars and user survey, conduct a report for submission

**Comment by DevArenaCN** [comment]
Let's keep the user meeting notes [here](https://docs.google.com/a/ncsu.edu/document/d/1DDpc6n4fV3IhqgETgoCY_edMnC3erDfRm0szOl5aFpQ/edit?usp=sharing)

**Comment by KaustubhG** [comment]
Paper:

Abstract - kg
Intro - kg
Literature Review - kg, harold, siddharth
Survey (User Study)
Conclusion

**Comment by KaustubhG** [comment]
I can do the abstract and the intro
We all can chip in for the lit. review.

**Comment by DevArenaCN** [comment]
Sounds good. Do you know how we can do the sharelatex without subscription? I can't find it anywhere

**Comment by KaustubhG** [comment]
https://www.sharelatex.com/user/bonus

If we refer each other, we can get the collaborator-editing feature free :)

**Comment by DevArenaCN** [comment]
I already have a sharelatex account...Can I refer any of you?

**Comment by KaustubhG** [comment]
sure. post your share-link here

**Comment by DevArenaCN** [comment]
Done. [Refer link](https://www.sharelatex.com?r=51e41f09&rm=d&rs=b)

**Comment by KaustubhG** [comment]
I registered. Did you get some notification?

**Comment by DevArenaCN** [comment]
Yes I did. Got 1 free collaborator. I'll create the latex file and add you guys into it. Let me know your username/email so I can do that

**Comment by KaustubhG** [comment]
Great! :-)
email: kgondha@ncsu.edu
username: kgondha

**Comment by DevArenaCN** [comment]
@KaustubhG Added.

**Comment by KaustubhG** [comment]
created a rough draft of abstract and intro.
Have a look.
Will work on the literature review tonight

**Comment by thegreyd** [comment]
Do you guys think literature review should come before user study? Because that's how we proceeded right?

**Comment by DevArenaCN** [comment]
@thegreyd Yeah that sounds good.

**Comment by thegreyd** [comment]
Hi Harold, can you explain the tradeoff table, "offline ability" parameter. I would assume it's when you can't access internet/network.

**Comment by DevArenaCN** [comment]
@thegreyd  Yeah that's what exactly what I meant.

**Comment by KaustubhG** [comment]
@thegreyd @DevArenaCN 
Added content under 'existing solutions' under Literature reivew.
Am now reviewing and editing minor stuff in the report

**Comment by DevArenaCN** [comment]
I've used grammarly to check the content for spelling errors last night, might missed something here and there. Keep us posted. I already take a look and it looks good to me.

**Comment by thegreyd** [comment]
Guys there's a problem with the formatting of citations. In Latex, citations are not written in text, but their Bibtex files are entered in a different file, and then referenced from there.

**Comment by DevArenaCN** [comment]
Report is uploaded onto GitHub, can be found [here](https://github.com/SE17GroupH/SE17_TeamH_Ideas/blob/master/January_report.pdf)

**Comment by KaustubhG** [comment]
I made some minor edits in the report and have pushed the changes to github too.

@thegreyd @DevArenaCN  you guys too review it once for any mods required.

Also remember we have to add the chits when we finally submit the report!

**Comment by thegreyd** [comment]
I have pasted the link to the report in the course spreadsheet: http://tiny.cc/reportjanH. 
Add the chits in the report? Then wouldn't they be public?

**Comment by DevArenaCN** [comment]
I'm going to add the chits into the report and update there file first thing tomorrow. Great work guys!

**Comment by DevArenaCN** [comment]
It's done. Closing this issue now. Great work guys!
