### ISSUE TITLE
Need input on topic: Meeting new people

### ISSUE THREAD

**Issue by DevArenaCN** [SE17GroupH/SE17_TeamH_Ideas#8]
Couldn't find results on this topic, I may have used the wrong keyword for this, need some input.

**Comment by thegreyd** [comment]
In simple words, meeting/chatting with people near your location to do activities in that area.

 Keywords I can think of: Location, local, meetup; might be difficult to find literature.

**Comment by KaustubhG** [comment]
I tried keywords like: expanding/extending social circle, discovering new social circles; didn't find any relevant literature :-(

**Comment by DevArenaCN** [comment]
Yep, I tried the same and couldn't find too much useful stuff. Guess we will just leave this one out.
