### ISSUE TITLE
Password Management

### ISSUE THREAD

**Issue by KaustubhG** [SE17GroupH/SE17_TeamH_Ideas#9]
-visual (PNC bank picture)
-typing pattern
-phrase
-password substitution
-finger print hash for master password
-QR code
-2 factor auth using QR code

Survey
-how do you feel about password substitution
-how often do you let others log in with your password ( typing pattern goes kaput if this is true)

**Comment by DevArenaCN** [comment]
- [x] Find literature to back up those implementations.

- [x] Find API calls, platforms to implement three ways to solve the problem.

- [x] Come up with a way to evaluate those implementations.

**Comment by thegreyd** [comment]
Some surverys
- https://www.surveymonkey.com/r/password-survey
- https://www.roboform.com/blog/password-security-survey-results

**Comment by thegreyd** [comment]
Browser extension 
- https://github.com/pfn/passifox/

**Comment by DevArenaCN** [comment]
Move this issue to Prepare Deliverables

**Comment by DevArenaCN** [comment]
Done with this issue. Closing it now
